import globals from "globals";
import { readFileSync } from "node:fs";

// The five files in public/ are classic <script>s sharing one global scope.
// tools/app-globals.json (generated by `npm run globals`) lists every
// top-level symbol so `no-undef` catches a real typo (a function called
// but defined nowhere) instead of every cross-file reference.
const appGlobals = JSON.parse(readFileSync(new URL("./tools/app-globals.json", import.meta.url), "utf8"));
const appGlobalMap = Object.fromEntries(appGlobals.map((n) => [n, "writable"]));

export default [
  { ignores: ["node_modules/**", "tests/.shots/**"] },
  {
    files: ["public/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        ...globals.browser,
        // CDN libraries loaded in index.html
        supabase: "readonly", Chart: "readonly", jspdf: "readonly",
        ...appGlobalMap,
      },
    },
    rules: {
      "no-undef": "error",
      "no-dupe-keys": "error",
      "no-dupe-args": "error",
      "no-duplicate-case": "error",
      "no-unreachable": "error",
      "no-constant-condition": "error",
      "no-empty": ["error", { allowEmptyCatch: true }],
      "valid-typeof": "error",
      // builtinGlobals:false — declaring one of our own configured globals in
      // its home file is the point, not a redeclaration.
      "no-redeclare": ["error", { builtinGlobals: false }],
      "no-self-assign": "error",
      "no-unsafe-negation": "error",
      "use-isnan": "error",
    },
  },
  {
    files: ["tools/**/*.mjs"],
    languageOptions: { ecmaVersion: 2022, sourceType: "module", globals: { ...globals.node } },
    rules: { "no-undef": "error" },
  },
  {
    // Test files mix Node (the runner) with page.evaluate callbacks that run
    // in the browser against the app's globals, so no-undef is not useful here.
    files: ["tests/**/*.mjs"],
    languageOptions: { ecmaVersion: 2022, sourceType: "module", globals: { ...globals.node, ...globals.browser, ...appGlobalMap } },
    rules: { "no-undef": "off", "no-unused-vars": "off" },
  },
];
